### ISSUE TITLE
need help in RLT 

### ISSUE THREAD

**Issue by lagkdok** [RobiNN1/PHP-Fusion-Themes#1]
hello
i'm working on PHP Fussion v9 Arabic edition, I'll be finish soon with all Locale files. I've little issue when i tried to change this Amdin theme into RTL direction. so are there changes in the inc files of the theme? because i think all my works in css files were fine.. so, please I need some help.

**Comment by RobiNN1** [comment]
In acp_styles.css  add  `body { direction: rtl; }`

**Comment by RobiNN1** [comment]
I made few edits  https://gist.github.com/RobiNN1/749fdf4bb46bb3f5f476f52e2767e4e2

**Comment by lagkdok** [comment]
god blessed you 
just one more question please check this picture labels are on the left i tried to turn it right but noway also the combo select must be on the right
[https://www.ouarsenis.com/up/uploads/ouarsenis.comSans-titre_5130c.png](url)

**Comment by RobiNN1** [comment]
Add to styles
```css
.form-group label {
  float: right;
}
```
